---

- name: 'Test playbook to sleep for a specified interval'
  hosts: all
  gather_facts: false
  vars:
    sleep_interval: 30

  tasks:
    - wait_for:
        timeout: "{{ sleep_interval }}"
      delegate_to:
        localhost